### ISSUE TITLE
[BUG] - 425 Error while transfering data: ECONNABORTED - Connection aborted while using put_file command

### ISSUE THREAD

**Issue by fervand1** [veeso/suppaftp#95]
## Description

I get error when trying to run put_file method, Error is 425 Error while transfering data: ECONNABORTED - Connection aborted while using put_file command. The issue occurs on latest filezilla server setup for FTP over TLS connections on localhost
All other commands work fine including RETR but only for uploading it creates the file correctly but with empty data.

## Steps to reproduce
Example code to try
```
let mut buffer = Vec::new();
let mut f = fs::File::open("test5.txt").expect("Failed to open file");
f.read_to_end(&mut buffer).expect("Failed to read file");
let _ = ftp_stream.put_file("test5.txt", &mut Cursor::new(buffer));
println!("Stored file 'test5.txt' on the server");
```
The program succeeds and prints Stored file 'test5.txt' on the server but the file is blank and the server has errors

![image](https://github.com/user-attachments/assets/53b36413-714a-4f70-9f06-021e0eb6d6d9)

Steps to reproduce the bug you encountered

## Expected behaviour
File should be uploaded correctly with all data

File upload to succed

## Environment

- OS: Windows 11
- Rust version: 1.83.0
- library version: 6.0.3
- Protocol used: FTP over TLS (FTPS) via rustls
- Remote server version and name: FileZilla Server 1.9.4

## Additional information
Since RETR works fine, I expect my passive mode for the server is setup correctly is working correctly which means there is no port issue. All other commands work fine except for STOR

EDIT: Following is a rough script that I was working with

```
use std::fs;
use std::io::{Cursor, Read};
use std::sync::Arc;
use suppaftp::{RustlsFtpStream, RustlsConnector, FtpError, FtpResult};
use suppaftp::rustls::ClientConfig;
use std::io::BufReader;


fn main(){
    // Creation of the Root Cert Store
    let mut root_cert_store = rustls::RootCertStore::empty();
    let mut pem = BufReader::new(std::fs::File::open("D:\\temp_cert\\cert.pem").unwrap());
    let certs = rustls_pemfile::certs(&mut pem);
    for cert in certs {
        match cert {
            Ok(cert) => {
                // Add the certificate to the root_cert_store
                if root_cert_store.add(cert).is_err() {
                    eprintln!("Failed to add certificate to root_cert_store");
                }
            }
            Err(err) => {
                eprintln!("Error reading certificate: {}", err);
            }
        }
    }
    

    // Create a configuration for the FTPS client.
    let config = ClientConfig::builder()
        .with_root_certificates(root_cert_store)
        .with_no_client_auth();

    // Create a connection to an FTP server and authenticate to it.
    let rc_config = Arc::new(config);

    // Connect to the FTP server.
    let mut ftp_stream = RustlsFtpStream::connect("127.0.0.1:21")
        .unwrap()
        .into_secure(RustlsConnector::from(rc_config), "127.0.0.1")
        .unwrap();

    // Log in to the FTP server.
    ftp_stream.login("testuser", "test$123456")
        .expect("Failed to log in to FTP server");

    println!("Successfully connected and logged in!");

    // Retrieve the current working directory.
    match ftp_stream.pwd() {
        Ok(current_dir) => println!("Current directory: {}", current_dir),
        Err(e) => eprintln!("Error retrieving current directory: {}", e),
    }

    // Create a new directory on the server.
    let _ = ftp_stream.mkdir("temp");

    // Change the working directory to the new directory.
    match ftp_stream.nlst(Some("/")) {
        Ok(dir_list) => {
            println!("Directory listing:");
            for entry in dir_list {
                println!("{}", entry); // Print each entry
            }
        }
        Err(e) => eprintln!("Error listing directory: {}", e), // Handle any errors
    }

    // Change the working directory to the new directory.
    let _ = ftp_stream.cwd("temp");

    // Retrieve the current working directory.
    let pwd = ftp_stream.pwd();
    match pwd {
        Ok(path) => println!("Successfully cwd! {}", path),
        Err(err) => eprintln!("Error changing working directory: {}", err),
    }
    
    // Retrieve the current working directory.
    match ftp_stream.nlst(Some(".")) {
        Ok(dir_list) => {
            println!("Directory listing:");
            for entry in dir_list {
                println!("{}", entry); // Print each entry
            }
        }
        Err(e) => eprintln!("Error listing directory: {}", e), // Handle any errors
    }

    let _ = ftp_stream.cdup();

    // Retrieve a file using `retr_as_buffer`
    let file_name = "test.txt";
    match retr_as_buffer(&mut ftp_stream, file_name) {
        Ok(buffer) => {
            println!("Successfully retrieved the file '{}'", file_name);
            println!(
                "File content:\n{}",
                String::from_utf8_lossy(&buffer.into_inner())
            );
        }
        Err(e) => eprintln!("Error retrieving file '{}': {}", file_name, e),
    }

    // Store a file on the server.
    // let file_name = "test.txt";
    // let file_content = b"Hello, world!";
    // let _ = ftp_stream.put_file(file_name, &mut Cursor::new(file_content));
    // println!("Stored file '{}' on the server", file_name);

    let mut buffer = Vec::new();
    let mut f = fs::File::open("test5.txt").expect("Failed to open file");
    f.read_to_end(&mut buffer).expect("Failed to read file");
    let _ = ftp_stream.put_file("test5.txt", &mut Cursor::new(buffer));
    println!("Stored file 'test5.txt' on the server");

    // // delete the file
    // let _ = ftp_stream.rm(file_name);
    // println!("Deleted file '{}'", file_name);
    
    // Terminate the connection to the server.
    let _ = ftp_stream.quit();
}


/// Retrieve a file from the server as a memory buffer.
fn retr_as_buffer(
    ftp_stream: &mut RustlsFtpStream,
    file_name: &str,
) -> FtpResult<Cursor<Vec<u8>>> {
    ftp_stream.retr(file_name, |stream| {
        let mut buf = Vec::new();
        stream
            .read_to_end(&mut buf)
            .map(|_| Cursor::new(buf))
            .map_err(|e| FtpError::ConnectionError(e))
    })
}

```

**Comment by fervand1** [comment]
Note: I also explicitly tried [put_with_stream](https://docs.rs/suppaftp/6.0.5/suppaftp/struct.ImplFtpStream.html#tymethod.put_with_stream)< and finalize put with stream but end up with the same situation, file is getting created on the server with 0KB but data is missing

**Comment by fervand1** [comment]
Also tried bumping to latest suppaftp version 6.0.5 (looking at the changelogs was not expecting it work anyways), the issue persists

**Comment by fervand1** [comment]
I am observing a strange behaviour while I tried debugging a bit, the error seems to be happening at drop(stream) in finalize_put_stream method.
```
/// Finalize put when using stream
    /// This method must be called once the file has been written and
    /// [`ImplFtpStream::put_with_stream`] has been used to write the file
    pub fn finalize_put_stream(&mut self, stream: impl Write) -> FtpResult<()> {
        debug!("Finalizing put stream");
        // Drop stream NOTE: must be done first, otherwise server won't return any response
        drop(stream);
        trace!("Stream dropped");
        // Read response
        self.read_response_in(&[Status::ClosingDataConnection, Status::RequestedFileActionOk])
            .map(|_| ())
    }
```

The strange part is that when I use debugger the data transfer happens fine but filezilla still gives an error. It seems the drop is happening much quicker then expected and shutting incorrectly.

**Comment by fervand1** [comment]
Further update on the issue:
The issue seems to be happening only when stream is secured (FTP over TLS), I switched to test insecure plain FTP and upload worked successfully. So something weird happening when TLS is enabled, but the download function works fine so I still don't see issue with the configuration. I would expect the upload to be successful over TLS too

**Comment by fervand1** [comment]
Further update:
I did check on the server configuration and used Filezilla client and also a node js script. And both seem to handle STOR command over TLS correctly

Example nodejs script used for the test
```
const ftp = require('basic-ftp');
const fs = require('fs');

async function ftpOperations() {
    const client = new ftp.Client();
    client.ftp.verbose = true;

    try {
        // Connect to the FTPS server with a certificate
        await client.access({
            host: "127.0.0.1",
            user: "testvan",
            password: "test$123456",
            secure: true,
            secureOptions: {
                ca: fs.readFileSync("cert"), // Load the certificate file
                rejectUnauthorized: true // Ensure server authentication
            }
        });

        console.log("Connected to the server.");

        // List the directory contents
        const list = await client.list();
        console.log("Directory contents:", list);

        // Perform the STOR command to upload a file
        const filePath = "D:\\test5.txt"; // Path to the local file
        const remoteFileName = "xxxxxx.txt"; // Name of the file on the server

        await client.uploadFrom(filePath, remoteFileName);
        console.log(`File uploaded as ${remoteFileName}.`);
    } catch (error) {
        console.error("Error during FTP operations:", error);
    } finally {
        client.close();
    }
}

ftpOperations();
```

**Comment by ctz** [comment]
Hi!

Judging by the error from filezilla-server/GnuTLS, I had a brief look at suppaftp's source for [rustls's `send_close_notify`](https://docs.rs/rustls/latest/rustls/struct.CommonState.html#method.send_close_notify) function, but there are no calls to it. That means the data connection is not closed cleanly at the TLS level, and GnuTLS therefore cannot be sure when the data is fully received.

I think this was fixed for native-tls in #5, the rustls backend needs a similar fix.

**Comment by fervand1** [comment]
@veeso would it be possible to integrate this fix in the suppaftp crate?

**Comment by veeso** [comment]
@fervand1 Can you check by using this branch `45-rustls-close-stream` ?

**Comment by fervand1** [comment]
@veeso I did a quick check with the fix , but it didn't seem to fix the issue. Got the same error.

**Comment by fervand1** [comment]
@veeso the drop should be implemented I think also on the data stream? What had worked for me was this https://github.com/rustls/rustls/issues/2297#issuecomment-2567743836

**Comment by veeso** [comment]
That calls drop on the underlying stream when it's dropped.

I've tried to add this

```rust
if self.ssl_shutdown {
            let _ = self.stream.flush();
            self.stream.conn.send_close_notify();
            let _ = self.stream.conn.write_tls(&mut self.stream.sock);
        }
```

as shown in your example. Can you retry by updating the ref to the branch?

**Comment by fervand1** [comment]
@veeso the fix works for the latest commit! Tested few large files of .db, .txt and .zip extension upto 5GB for secured FTPs, seems all good. Thanks a ton

**Comment by veeso** [comment]
Excellent, thanks for testing.

I will release the patch tomorrow morning UTC

**Comment by fervand1** [comment]
@veeso sure thank you!
